### ISSUE TITLE
CopyLambdaArtifactsStack - TemplateURL must be a supported URL.

### ISSUE THREAD

**Issue by davidenegrini** [amazon-connect/voicemail-for-amazon-connect#101]
Hi, the cloudformation process using Dev Release 1.2.1 stops with "CopyLambdaArtifactsStack" raising error "TemplateURL must be a supported URL." giving "CREATE_FAILED" and then it starts the rollback.
Tried in region e-central-1.
<img width="578" alt="image" src="https://user-images.githubusercontent.com/7033399/236498484-885dd591-881a-404a-a62e-7befdc774178.png">
Thank you!

**Comment by phisada** [comment]
Same here using voicemail-for-amazon-connect.template from vmv1s3fix.


![lambda_artifacts](https://github.com/amazon-connect/voicemail-for-amazon-connect/assets/135070789/cdeadc60-44e7-479f-8143-08647efb7181)

**Comment by phisada** [comment]
I suppose it helps to read: "README"!  After creating the S3 bucket, uploading templates and editing the main template to insert the bucket name, stack creation completed without a problem.  Now on to the rest of the config.  
Thanks for your patience!

**Comment by virtualgill** [comment]
@davidenegrini Can you confirm if you are trying to use the preconfigured templates, or building them yourself from the dev branch? Thanks!

**Comment by phisada** [comment]
I used the preconfigured templates provided here: https://aws-contact-center-blog.s3.us-west-2.amazonaws.com/voicemail-s3-default-acl-issue/vmv1s3fix.zip.  It didn't work until per the readme  I created the S3 bucket and uploaded all the template files to it, then edited the code in the main template to indicate the location of the S3 bucket.

**Comment by angelacyu** [comment]
Hi @davidenegrini and @phisada. Whats the status? Is it working now after following the S3 bucket route?

**Comment by phisada** [comment]
Hi @angieyu, yes I can report that following that route worked for me. Thanks!

**Comment by davidenegrini** [comment]
Not tried yet but I looked at the template code and I guess you're right about it.
Anyway I haven't seen this information in the implementation guide (pdf) or in the readme files here on github (both master and developer branches) and I don't know where @phisada found that really helpful link for fixing.
Thank you for the help, I'll be deploying soon the voicemail service.

**Comment by virtualgill** [comment]
Just for completeness in case others are looking at this issue in future, the instructions and link to the additional steps are are at the top of the [README](https://github.com/amazon-connect/voicemail-for-amazon-connect/blob/master/README.md) in the master branch. The development branch is designed for people who want to build the templates themselves and deploy locally (rather than use the preconfigured ones). The changes for ACL are in the code in the dev branch, so when you run the builds from there to create the templates for yourself locally you will get updated ones generated.
