### ISSUE TITLE
Key Pair are visible for client 

### ISSUE THREAD

**Issue by ceciliapizzu** [amazon-connect/voicemail-for-amazon-connect#104]
Hi AWS, 

The affected JavaScript file contains sensitive information like client secrets that should not be placed in client-side code as they are discoverable without any authentication. 
Can you please fix it ? https://aws.amazon.com/solutions/implementations/voicemail-for-amazon-connect/

1. The file name(s) https://github.com/amazon-connect/voicemail-for-amazon-connect
2. Where the API Keys are exposed in the output of the cloudformation call.  

The file is in the portal bucket  that is sharing the Key Pair 
under the folder static/js/

**Comment by virtualgill** [comment]
Hi there!

The key you are seeing is the API Key for API Gateway and not used for authentication. The solution does not store any secrets client-side and uses Cognito for all authentication. The authentication is done through the [API Gateway Lambda authorizer](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html) found [here](https://github.com/amazon-connect/voicemail-for-amazon-connect/blob/development/aws-connect-vm-serverless/src/handler/authorizer.js).
The API Gateway Key is there so the solution can follow the best practice of implementing  a [Usage Plan ](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-usage-plans.html)(set initially to rate limit the API requests, 50/second and a burst of 500), and they are generated by APIG as part of the deployment as per [best practices](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-usage-plans.html#apigateway-usage-plans-best-practices).

We wouldn't recommend that you remove the APIG Key, but since this an open source project, you do have the option of modifying it for your own needs. If you wish to do that, we recommend using the [development branch](https://github.com/amazon-connect/voicemail-for-amazon-connect/tree/development) which has the latest changes, and has a simplified build process as [noted here](https://github.com/amazon-connect/voicemail-for-amazon-connect#development-branch).
