### ISSUE TITLE
Serverless Deploy

### ISSUE THREAD

**Issue by rvillegast** [amazon-connect/voicemail-for-amazon-connect#109]
Hi, i have a question... i need to change the mail template... but i can't deploy only the serverless side... how i can deploy only the serverless without run all the cloudformation template?

**Comment by monikadr** [comment]
I also have the same question, I need to add one additional field to the DynamoDB entries, TTL field so when transcribe is complete along with update status, I want to add one additional field for TTL. 

If I make the changes and build the lambda and upload it back to the same S3 bucket - and redeploy the code in Lambda will it work?

**Comment by monikadr** [comment]
Hello, Any update on this?

**Comment by virtualgill** [comment]
Hi there! The development branch is designed for those who would want to make changes to the solution. You should be able to use this to make changes and deploy all or part of it. I would recommend you fork this, make the changes, and test it out in a dev environment before production.

Cloudformation templates are designed so that when you deploy only resources that have been changed will be updated, however that will depend on the specifics of how you have deployed it. If you run it exactly the same as you did the first time with an updated lambda it should only make that update since the other resources will be up to date. It is possible also to just update a single lambda by directly uploading new code to it through the API or console (but you would want to be careful not to overwrite that accidentally in the future).

**Comment by monikadr** [comment]
I understand that we can use development branch. All the commands to build the solution ie., build.sh needs linux machine is there a script that I can use for windows machine?

**Comment by monikadr** [comment]
> I understand that we can use development branch. All the commands to build the solution ie., build.sh needs linux machine is there a script that I can use for windows machine?

I understand that we can use development branch. All the commands to build the solution ie., build.sh needs linux machine is there a script that I can use for windows machine?
