### ISSUE TITLE
Flow template from Generate Contact Flow

### ISSUE THREAD

**Issue by DPWindom** [amazon-connect/voicemail-for-amazon-connect#112]
Version 1.1.0 

I'm attempting to publish the flows generated from the voicemail management portal, but there is an issue with the VM-Agent flow. The "Loop prompts" blocks are tagged with "Unsupported block type", preventing the publish action.

I've attached the json generated from the portal and a screenshot of the errors in the flow editor.

[VM-Agent.json.txt](https://github.com/amazon-connect/voicemail-for-amazon-connect/files/12542683/VM-Agent.json.txt)
![Amazon Connect - VM-Agent flow error](https://github.com/amazon-connect/voicemail-for-amazon-connect/assets/106351425/f20b8750-9d6a-4948-8632-0956e616065e)

**Comment by DPWindom** [comment]
The error behavior appears to happen when you create a new flow and simply select "Create Flow". If you create a flow using the drop down list and select "Create Customer queue flow", the template will save and publish without error.

**Comment by virtualgill** [comment]
Hi there! Apologies for the confusion, but that behaviour is correct. There are different types of flows and each has different blocks supported. The flows in the solution require that the option listed in the instructions is chosen from the dropdown at "Create". The generic "Create contact flow" button creates an Inbound flow rather than the Customer Queue flow needed for the VM-agent.json
https://docs.aws.amazon.com/connect/latest/adminguide/create-contact-flow.html#contact-flow-types
