### ISSUE TITLE
Where to start when emails are not delievered?

### ISSUE THREAD

**Issue by DrVoIP** [amazon-connect/voicemail-for-amazon-connect#13]
I think we need clarification on this email configuration requirement.  It seems that Cognito is the resource for sending email messages. Further that the only email address that needs to be verified is the one that was used as a parameter in the CF for sender email address.  The doc does reference in Appendix A that SES needs to verify email?   Can we get some clarification on this.  In five deployments I have run into the same issue.  In this last on I get SMS and Transcriptions, but no Email.   What function launches the email and what logs can be used to figure out where email is broke?

Also can we leave issues published so we can all benefit from them even when they are resolved?

**Comment by efh365** [comment]
Just to be clear, it seems like your issue is that you are not getting emails delivered to agents whose emails are not verified, correct? If so, you will need to make sure you have requested production access to SES. Here is documentation on that: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html

I will update the docs to point to that resource to remove that confusion. You can find the logs for sending emails under the Lambda function that has "VoicemailStream" in its name. The email is sent in the notification.service.js file and is sent by SES and not Cognito.

For your comment on issues - are you not able to see the closed issues? From my understanding, once an issue is closed, users can still see it and search for closed issues. Open issues should only be for ones that do not have a resolution.

**Comment by DrVoIP** [comment]
E - We have SES limits established and email addresses are verified.  The question was:  Is Cognito sending the email or is SES?  In a previous issue the comment back was, only the sender email established by CF needs to be verified.  Now it seems that is not true? SES is used and all recipients must be verified?  What function initiates the email sending so we can track back to where this is broken.  All else works including SMS, but no email is being sent. (Media streaming is enabled).

**Comment by DrVoIP** [comment]
checking the logs for "voicemailstream". I think I may have found the issue.  The instance is in Sydney.  I will update this but I think I am on track now.

**Comment by DrVoIP** [comment]
Checking the cloudwatch logs for the log with "voicestreaming" in the title is a good place to start!  This issue turned out to be SES email verification in the wrong Region.  The instance was in Syndney and the SES is not a global.   I also found that you can search for issues = closed which is very helpful. Thanks all.
