### ISSUE TITLE
Voicemail prompt delay 

### ISSUE THREAD

**Issue by terrell-r** [amazon-connect/voicemail-for-amazon-connect#25]
A have a couple hold queues, setup with Get Customer input prompts to leave a voicemail, when the caller presses 1 to leave a voicemail the call is sent to a Transfer to phone number block with a DMTF code for the mailbox. Once the transfer completes theres a delay of 15 - 30 seconds before the caller hears the prompt to leave a voicemail.. you have 60 seconds. 

Is there a way to reduce or eliminate this delay, or a better way to transfer a call to a voicemail box without the caller needing to specify a mailbox extension?

**Comment by swalmsley11** [comment]
Since you mention a hold queue, I assume you are talking about a non-agent queue and that you're sending calls to a general voicemail box of sorts, and not an individual agent voicemail box. Is that the case?

**Comment by DrVoIP** [comment]
There is not reason to create a new phone call?  Since you can't transfer to flow within a customer queue hold flow, I assume that is where you put this transfer to number?   Set a contact attribute to extension number and copy the flow from the original prompt for extension number greeting, to the leave voice mail option.   I setup queues as users so they have voice mail funcionality and code my queue hold flow as described, works flawlessly.

**Comment by efh365** [comment]
Hi Terrell-r. Did either suggestion solve your problem? If not, is there anything else we can do to help provide guidance?

**Comment by terrell-r** [comment]
@efh365 Yes thank you mostly, I've switched from transferring voicemail requests via a Transfer to phone number block to creating an inbound contact flow and pasting everything after the Invoke AWS Lambda function block in the new contact flow for handling in call voicemail transfers as @DrVoIP suggested. This setup doesn't work for customer queues of course
