### ISSUE TITLE
AWS Lambda end of support for Node.js 10

### ISSUE THREAD

**Issue by mardinir** [amazon-connect/voicemail-for-amazon-connect#56]
AWS is ending support for Node.js 10 in Lambda on July 30, 2021 [1]. This follows the Node.js language governing body declaring Node.js 10 end of life as of April 30, 2021.

What are the plans for this solution to migrate the existing Node.js 10 Lambda functions to a supported runtime e.g., Node.js 14?

[1] https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

**Comment by Vigrond** [comment]
In case anyone was worried that their app would stop functioning:

`Lambda does not block invocations of functions that use deprecated runtime versions. Function invocations continue indefinitely after the runtime version reaches end of support. However, AWS strongly recommends that you migrate functions to a supported runtime version so that you continue to receive security patches and remain eligible for technical support. `

https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

**Comment by khastation** [comment]
@mardinir  We've updated the lambda runtime to nodejs12.X on the dev branch, please test and let us know if that works for you!

**Comment by ghenson213** [comment]
@khastation My initial testing looks good. I see three Lambdas were not moved to NodeJS12.x 
- CopyArtifactsHelperFunction
- SolutionHelperFunction
- CloudfrontHelperFunction
They seem to be defined in the deployment templates and not the serverless.yml.

Was moving the functions to NodeJS14.x tested but not feasible right now?

Thank you

**Comment by khastation** [comment]
@ghenson213 @mardinir we've updated nodejs10.X to nodejs12.X in the main repository now.
