### ISSUE TITLE
CloudFormation stack create failing on creating AudioRecordingsBucket

### ISSUE THREAD

**Issue by balukadiyala** [amazon-connect/voicemail-for-amazon-connect#97]
Running the sam deploy aws-connect-vm.template with required parameters in us-east-1 getting below error:

The target bucket for logging does not exist (Service: Amazon S3; Status Code: 400; Error Code: InvalidTargetBucketForLogging; Request ID: W7TGBGR85FX25NPW; S3 Extended Request ID: 1R8N/23GoKAaWnSGw8kyt+tX3SeeBE6+T9QiPJu3Ockg031+EnZ8IT8JWM+GDBMw/XS7hk29gFw=; Proxy: null)

**Comment by PrasadPotale** [comment]
Check this comment, i have just used the template url mentioned and it worked fine for us,
https://github.com/amazon-connect/voicemail-for-amazon-connect/issues/92#issuecomment-1323300616

**Comment by virtualgill** [comment]
Hi @balukadiyala - are you still having issues?

These are two ways of deploying this, either you can use the cloudformation template linked in the pdf instructions (https://s3.amazonaws.com/solutions-reference/voicemail-for-amazon-connect/latest/voicemail-for-amazon-connect.template) or you can use the one in the github repo. If you are using the one in the github repo it's important that you follow the steps in the README first to build and populate it with the right values. Can I check which method you are using? 

If you want to use the pre-populated template you will also need to use the updated files and instructions here: https://aws-contact-center-blog.s3.us-west-2.amazonaws.com/voicemail-s3-default-acl-issue/vmv1s3fix.zip (detailed at the top of the [README](https://github.com/amazon-connect/voicemail-for-amazon-connect))

**Comment by anchalmarwah** [comment]
Hi,
I had similar issues today.
So the solution to it will be you can upload the aws-connect-vm template in your s3, modify the [voicemail-for-amazon-connect](https://github.com/amazon-connect/voicemail-for-amazon-connect/tree/master) template to point it to the s3 location you stored the aws-connect-vm template, as the error you are getting is because your master template is referencing to old aws-connect-vm template in the "Solutions" S3 bucket and S3 key, which is not having updated policy. It should resolve the error, just did it now and resolved for me. Hope it helps.
